
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aykzhgjywakjzkphokco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5a3poZ2p5d2FranprcGhva2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDkwNjAsImV4cCI6MjA2MjEyNTA2MH0.-gcFBpyRJ2xgnA4g2Lxtk9Dhu_uVTTOXJXygu48g1hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'caterdirectly-auth',
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
